apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Josh\documents\github\kompose.exe convert -c
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}
