apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Josh\documents\github\kompose.exe convert -c
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
